export { default as Hero } from './Hero'
export { default as CapitalGain } from './CapitalGain'
export { default as Likes } from './Likes'
export { default as Presentation } from './Presentation'
export { default as Stories } from './Stories'
export { default as Uses } from './Uses'
